export const listItem = [
   {
      id: 1,
      img: "./images/husky.jpg",
      category: "Chó",
      address: "Hà Nội",
      name: "BẦY PUG MẶT XỆ THUẦN CHỦNG BABY",
      rating: 4,
      author: "Nguyễn Văn Nam",
      price: 3500000,
      gender: "đực",
   },
   {
      id: 2,
      img: "./images/husky.jpg",
      category: "Chó",
      address: "Hà Nội",
      name: "BẦY PUG MẶT XỆ THUẦN CHỦNG BABY",
      rating: 4,
      author: "Nguyễn Văn Nam",
      price: 3500000,
      gender: "đực",
   },
   {
      id: 3,
      img: "./images/husky2.jpg",
      category: "Chó",
      address: "Hà Nội",
      name: "BẦY PUG MẶT XỆ THUẦN CHỦNG BABY",
      rating: 4,
      author: "Nguyễn Văn Nam",
      price: 3500000,
      gender: "đực",
   },
   {
      id: 4,
      img: "./images/husky2.jpg",
      category: "Chó",
      address: "Hà Nội",
      name: "BẦY PUG MẶT XỆ THUẦN CHỦNG BABY",
      rating: 4,
      author: "Nguyễn Văn Nam",
      price: 3500000,
      gender: "đực",
   },
   {
      id: 5,
      img: "./images/husky.jpg",
      category: "Chó",
      address: "Hà Nội",
      name: "BẦY PUG MẶT XỆ THUẦN CHỦNG BABY",
      rating: 4,
      author: "Nguyễn Văn Nam",
      price: 3500000,
      gender: "đực",
   },
   {
      id: 6,
      img: "./images/husky2.jpg",
      category: "Chó",
      address: "Hà Nội",
      name: "BẦY PUG MẶT XỆ THUẦN CHỦNG BABY",
      rating: 4,
      author: "Nguyễn Văn Nam",
      price: 3500000,
      gender: "đực",
   },
   {
      id: 7,
      img: "./images/husky2.jpg",
      category: "Chó",
      address: "Hà Nội",
      name: "BẦY PUG MẶT XỆ THUẦN CHỦNG BABY",
      rating: 4,
      author: "Nguyễn Văn Nam",
      price: 3500000,
      gender: "đực",
   },
   {
      id: 8,
      img: "./images/husky2.jpg",
      category: "Chó",
      address: "Hà Nội",
      name: "BẦY PUG MẶT XỆ THUẦN CHỦNG BABY",
      rating: 4,
      author: "Nguyễn Văn Nam",
      price: 3500000,
      gender: "đực",
   },
];
